on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: windows-latest
    steps:
        # Checkout the main branch
    - uses: actions/checkout@main
    
    - name: Install Modules
      shell: pwsh
      run: |
        Set-PSRepository PSGallery -InstallationPolicy Trusted
        Install-Module InvokeBuild
    
    - name: Invoke Build
      env:
        NUGET_API_KEY: ${{ secrets.POWERSHELL_GALLERY }}
      shell: pwsh
      run: Invoke-Build Build, Publish

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: CMBuilder # Naming the powershell module artifact
        path: ./Output/ # Saving the powershell module artifact to the path ./Output/
        
